name: dbt_run_integration_test
run-name: ${{ github.event.inputs.branch }}

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  debug_vars:
    runs-on: ubuntu-latest
    environment:  ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
    steps:
      - name: Debug warehouse variable
        run: echo "Warehouse value is '${{ vars.WAREHOUSE }}'"

  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt.yml@main

    with:
      command: >
        dbt test --selector 'integration_tests'
      environment:  ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit