name: dbt_run_integration_test
run-name: ${{ github.event.inputs.branch }}

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt.yml@main
    with:
      command: >
        dbt test --selector 'integration_tests'
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit

  notify-failure:
    needs: [called_workflow_template]
    if: failure()
    uses: FlipsideCrypto/fsc-evm/.github/workflows/slack_notify.yml@main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
