version: 2 

sources:
  - name: github_actions
    database: "{{ target.database }}"
    schema: github_actions
    tables:
      - name: workflows
  - name: bronze_streamline
    database: streamline
    schema: >-
      {{ var('PROD_DB_NAME') ~ ('_dev' if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else '') }}
    tables:
      - name: blocks
      - name: transactions
      - name: >-
          {{ 'receipts_by_hash' if var("USES_RECEIPTS_BY_HASH", False) else 'receipts' }}
      - name: traces
      - name: confirm_blocks
      - name: decoded_logs
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database.upper() == var('PROD_DB_NAME').upper() else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: labels_combined